version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  certificate:
    container_name: certificate
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: password
      POSTGRES_PASSWORD: mydb1
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./data/pg/db:/var/lib/postgresql/data
